services:
  recorder:
    image: ghcr.io/t9a-dev/radyko:latest
    # build:
    #   context: .
    command: ["recorder", "-c", "radyko.toml"]
    volumes:
      - ./radyko.toml:/app/radyko.toml
      - ./recorded:/app/recorded
    env_file:
      - .env
    logging:
      driver: local
      options:
        max-file: '5'
        max-size: 10m
