# https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
name: CI for Forgejo

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
    - uses: actions/checkout@v6
    - uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
    - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
    - name: Build
      run: cargo build --verbose
    - name: Random delay
      run: |
        sleep $((RANDOM % 1800))  # 0〜1799秒ランダム待機
    # セルフホストしているForgejoでradiko WebAPIを利用するテストも含めて実行する
    - name: Run tests
      env:
        RADIKO_AREA_FREE_MAIL: "${{ secrets.RADIKO_AREA_FREE_MAIL }}"
        RADIKO_AREA_FREE_PASSWORD: "${{ secrets.RADIKO_AREA_FREE_PASSWORD }}"
      run: cargo test --verbose -- --include-ignored --show-output --test-threads=1
