# https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
name: CI for Forgejo

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
    - name: Random delay
      run: |
        sleep $((RANDOM % 3600))  # 0〜3599秒ランダム待機
    - uses: actions/checkout@v6
    - name: Install Dependecies
      run: |
        sudo apt update
        sudo apt install -y build-essential
    - uses: rui314/setup-mold@v1
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose
    # セルフホストしているForgejoでradiko WebAPIを利用するテストも含めて実行する
    - name: Run tests
      env:
        RADIKO_AREA_FREE_MAIL: "${{ secrets.RADIKO_AREA_FREE_MAIL }}"
        RADIKO_AREA_FREE_PASSWORD: "${{ secrets.RADIKO_AREA_FREE_PASSWORD }}"
      run: cargo test --verbose -- --include-ignored --show-output --test-threads=1
