# https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
name: Build & Test

on:
  push:
    paths:
      - "**/*.rs"
      - "Dockerfile"
  pull_request:
    paths:
      - "**/*.rs"
      - "Dockerfile"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build Docker image
        run: |
          docker build \
            --tag radyko:ci \
            .
      - name: Smoke test Docker image
        run: |
          docker run --rm radyko:ci --version
