# https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
name: Build & Test

on:
  push:
    paths:
      - "**/*.rs"
      - "Dockerfile"
  pull_request:
    paths:
      - "**/*.rs"
      - "Dockerfile"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Build Docker image (with cache)
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f #v7.1.0
        with:
          context: .
          tags: radyko:ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Smoke test Docker image
        run: |
          docker run --rm radyko:ci --version